### ISSUE TITLE
Purifier doesnt seem to work

### ISSUE THREAD

**Issue by sprocketaudio** [CreeperEntertain/CE-s-Minerals-More#2]
Purifier has no 'use' recipes in JEI and I cant find what to put in it.. looking at advancements I also cant see how to make diamond or emerald shards from it?

It is powered and I have tried putting many different vanilla items in it

1.20.1

**Comment by CreeperEntertain** [comment]
I will add JEI compatibility in the future. The way it is done right now is that you have to use the menu opened via /instructions to find the recipes. Thanks for putting my attention on the pure carbon. In the Purifier, the only item that transforms into shards is graphite. Even though it makes sense for that to work, I forgot to implement pure carbon.

I will also add a button to the UIs that brings up their recipe pages directly.

Thanks for reporting!

**Comment by sprocketaudio** [comment]
Ok thanks for the response and the great mod! I am looking at designing a questing modpack around it so want to be sure I fully understand all the progression! I did look in the /instructions for help with the purifier but it is not listed as a machine anywhere unless I mised it?

![image](https://github.com/user-attachments/assets/036b0f8c-2982-418b-8023-6708d684e19a)
![image](https://github.com/user-attachments/assets/f099bfe0-1290-4239-acfd-021a2251e1f2)
![image](https://github.com/user-attachments/assets/8244f9ff-3142-443f-8969-c126edb2f5c8)

Maybe there is more to come and I am happy to wait - a button in each machine to take to the needed information would be perfect :)

**Comment by CreeperEntertain** [comment]
The purifier was more intended to be the sorta block where you throw stuff in and see what comes out. As such, I didn't really add a recipe page for it, but I understand why that's confusing. It's going to be added in the future.

**Comment by sprocketaudio** [comment]
> The purifier was more intended to be the sorta block where you throw stuff in and see what comes out. As such, I didn't really add a recipe page for it, but I understand why that's confusing. It's going to be added in the future.

This is fine as a concept tbh, but yeah I guess jsut wasnt sure!

**Comment by CreeperEntertain** [comment]
Update: I reworked the purifier, and it's going to release with the other changes in the next week or so. Also implemented a rebalance. Things should now be smooth sailing.

**Comment by CreeperEntertain** [comment]
As an added note: I am unsure whether I want to implement JEI integration. I see why it would be useful, but A: I want people to be surprised with the recipes, and B: I want players to actually interact with the workstations for the recipes.

**Comment by sprocketaudio** [comment]
I get you - its difficult.. Sometimes making the player do something the causes friction makes them not do it at all.. JEI/REI etc are the 'standard' way to find recipes so I think, if you do not want to use it, I think firstly make it clear that is your plan in your guide right at the beginning (so players know where to look) and also make sure your guide is clear and user friendly enough to stop the player feeling like its a 'turn off' for the mod. 

I am not specifically commenting on your guide here above, was more a general set of thoughts. If I was to comment on your guide I'd say that although it does have a lot of info in, its almost too much text and hard to see whats important due to small fonts/icons, at least until you know what you are looking for.

**Comment by CreeperEntertain** [comment]
The plan here, which I'm working on right now, is giving the player a book when they join the world, with which they can read some basic info on the mod's premise, as well as open the instruction menu, etc., hinting them at the advancement tree, and informing them that /instructions and /goals exist.
