### ISSUE TITLE
Suggestion: Add chemical symbols to raw/base item names

### ISSUE THREAD

**Issue by sprocketaudio** [CreeperEntertain/CE-s-Minerals-More#4]
Please consider adding the chemical symbol for each element you use in the rawest form item name -

Example.. was looking in your /instructions for where to mine antimony, but had to leave game and goolge it to know it was listed as SB in your guide..

![image](https://github.com/user-attachments/assets/fcc47efa-d83e-4fa0-a9a5-655df2b1ade8)
![image](https://github.com/user-attachments/assets/37149ccf-4df1-4a00-85e7-9a26829ed917)

Maybe something like "Raw Anitmony (Sb)"

I know most are obvious, but consider many people not from a science background (and I am, but didnt know Sb!) might not know where to start with this!

**Comment by CreeperEntertain** [comment]
Oh, that's an interesting idea. Yeah, will definitely do that. Will have to decide whether it becomes part of the name or the item description, but I will probably rewrite the names, e.g.: Wolframite (W), Dolomite (Ca, Mg), ... .
As such, the issue will stay open until implemented.

**Comment by CreeperEntertain** [comment]
I'm a bit late to comment, but the change has been implemented and will be pushed out with the new release.
