### ISSUE TITLE
Possible bug/suggestion: - Stop mouse from resetting in guide book

### ISSUE THREAD

**Issue by sprocketaudio** [CreeperEntertain/CE-s-Minerals-More#5]
When you click the next arrow, or previous arrow in the guide book, the mouse resets to centre of the screen so you can't click multiple times in a row without moving mouse again.

![image](https://github.com/user-attachments/assets/e5f6bbbd-da43-4bae-912e-8a7c9d8491c4)

**Comment by CreeperEntertain** [comment]
The way the UI works is that each page is a UI itself. Controlling the mouse for the pages requires more mixins that could potentially introduce incompatibilities. Minecraft has a paging system for UIs, but I wasn't able to pull of implementing it. I'll likely see what I can do in the future, but I will temporarily close it as not planned. Hope you understand.
