### ISSUE TITLE
Tantalum (Ta) is not listed in instructions

### ISSUE THREAD

**Issue by sprocketaudio** [CreeperEntertain/CE-s-Minerals-More#6]
I cant find Tantalum (Ta) in the guide book in the where to mine section..

![image](https://github.com/user-attachments/assets/1596f182-3cba-48c1-88c0-348a490a8b96)

**Comment by CreeperEntertain** [comment]
Materials that are side products from other materials are not on this page. This page is purely for mining, and some materials are found in trace amount as part of other resources. For that, skim through the recipes.
